name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  test:
    runs-on: [ windows-latest ]

    steps:
    - uses: actions/checkout@v4
    
    - name: Checkout code
      uses: actions/checkout@v4 #update

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean install

    - name: Upload Cucumber JSON Report
      uses: actions/upload-artifact@v4  
      with:
        name: cucumber-json-report
        path: target/cucumber-report.json
    
    - name: Upload Cucumber HTML Report
      uses: actions/upload-artifact@v4  
      with:
        name: cucumber-html-report
        path: target/html-report.html
